# Generated by Django 4.1.3 on 2022-11-24 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='имя')),
                ('surname', models.CharField(blank=True, max_length=200, verbose_name='фамилия')),
                ('patronymic', models.CharField(blank=True, max_length=200, verbose_name='отчество')),
                ('phone', models.CharField(max_length=200, verbose_name='телефон')),
            ],
        ),
        migrations.CreateModel(
            name='Appeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='текст обращения')),
                ('created', models.DateField(auto_now_add=True, verbose_name='дата создания')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appeals', to='api.client', verbose_name='клиент')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
